name: Daily Fliff Parlay

on:
  schedule:
    - cron: "30 12 * * *" 
  workflow_dispatch: {}      # lets you manually trigger a run from GitHub's UI to test

jobs:
  run-parlay:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: pip install -r requirements.txt

      - run: python main.py
        env:
          THE_ODDS_KEY: ${{ secrets.THE_ODDS_KEY }}
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
          RUN_MODE: live